version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017
clone_depth: 1
before_build:
- cmd: nuget restore SpaceStation14.sln

build:
  project: SpaceStation14.sln
  parallel: true
  verbosity: minimal

install:
- cinst python

after_build:
- cmd: py -3 Resources\buildResourcePack.py --resources-dir .\Resources --out .\Resources\ResourcePack.zip --sprite-renderer .\Resources\SpriteRenderer\MSpriteRenderer.exe --atlas-tool .\Tools\AtlasTool.exe

test: off
